version: 4.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    Start-FileDownload 'https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe' -FileName 'C:\DXSDK_Jun10.exe'

    Start-FileDownload 'https://github.com/chocolatey/chocolatey/raw/master/src/redirects/RefreshEnv.cmd' -FileName 'C:\RefreshEnv.cmd'

    Start-Process "C:\DXSDK_Jun10.exe" "/F /S /O /U" -NoNewWindow -Wait
install:
- cmd: >-
    C:\RefreshEnv.cmd

    git submodule update --init --recursive

    premake5.bat
build:
  project: build/Ultimate-ASI-Loader-x86.sln
  verbosity: minimal
before_package:
- cmd: msbuild.exe build/Ultimate-ASI-Loader-x64.sln /t:Build /p:Configuration=Release;Platform=x64
after_build:
- cmd: release.bat
artifacts:
- path: bin\Ultimate-ASI-Loader.zip
  name: Ultimate-ASI-Loader.zip
- path: bin\Ultimate-ASI-Loader_x64.zip
  name: Ultimate-ASI-Loader_x64.zip
- path: bin\RE7Demo.InfiniteAmmo.zip
  name: RE7Demo.InfiniteAmmo.zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Ultimate ASI Loader v$(appveyor_build_version)
  description: DESCRIPTION\n------------------------\nThis is a DLL file which adds ASI plugin loading functionality to any game, which uses any of the following libraries:\n* d3d8.dll\n* d3d9.dll\n* d3d11.dll\n* ddraw.dll\n* dinput.dll\n* dinput8.dll (x86 and x64)\n* dsound.dll (x86 and x64)\n* msacm32.dll\n* msvfw32.dll\n* vorbisFile.dll\n* winmmbase.dll\n* xlive.dll\n\n\nINSTALLATION\n------------------------\nIn order to install it, you just need to place DLL into game directory. Usually it works as dinput8.dll, but if it's not, there is a possibility to rename it(see the list of supported names above).
  auth_token:
    secure: SXMI7bm5RKh5j1S8A8dnUP2HFw97xHHlJH+mA0hx819vtxOPCpMFY3aFZ+2v16ri
  artifact: Ultimate-ASI-Loader.zip, Ultimate-ASI-Loader_x64.zip